const ROLES = {
  ADMIN: 'ADMIN',
  TEAM_LEAD: 'TEAM_LEAD',
  FIELD_WORKER: 'FIELD_WORKER',
};

const ATTENDANCE_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  FLAGGED: 'FLAGGED',
  REJECTED: 'REJECTED',
};

const LEAVE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

const REPORT_STATUS = {
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

const TASK_STATUS = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

module.exports = { ROLES, ATTENDANCE_STATUS, LEAVE_STATUS, REPORT_STATUS, TASK_STATUS };
